version: '3.7'
x-datavis-backend: &datavis-backend-prod
  image: guwenqing/datavis-backend:latest
  depends_on:
    - postgres-prod
    - redis-prod
  restart: always
services:
  redis-prod:
    image: redis:3-alpine
    restart: unless-stopped
  postgres-prod:
    image: postgres:9.5-alpine
    volumes:
      - /opt/datavis/postgres_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  server-prod:
    <<: *datavis-backend-prod
    command: server
    ports:
      - "30056:5000"
    volumes:
      - /opt/datavis/uploads:/app/uploads
    environment:
      REDASH_REDIS_URL: "redis://redis-prod:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres-prod/postgres"
      REDASH_WEB_WORKERS: 2
  worker-prod:
    <<: *datavis-backend-prod
    command: scheduler
    volumes:
      - /opt/datavis/uploads:/app/uploads
    environment:
      REDASH_REDIS_URL: "redis://redis-prod:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres-prod/postgres"
      QUEUES: "queries,scheduled_queries,celery,schemas"
      WORKERS_COUNT: 2
  frontend-dashboard-prod:
    image: guwenqing/datavis-dashboard:latest
    restart: always
    ports:
      - "30096:80"
    environment:
      PORT_BACKEND_SERVER: 30056
      PORT_FRONTEND_DASHBOARD: 30096
networks:
  default:
    name: datavis-network-prod
