apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
  namespace: datavis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
      - name: pg-volume
        persistentVolumeClaim:
          claimName: pg-volume-claim
      restartPolicy: Always
      containers:
      - name: postgres
        image: postgres:9.5-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: pg-volume
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
  namespace: datavis
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres