apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
  namespace: datavis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
      - name: uploads-volume
        persistentVolumeClaim:
          claimName: uploads-volume-claim
      restartPolicy: Always
      containers:
      - name: worker
        image: guwenqing/datavis-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/uploads
          name: uploads-volume
        env:
        - name: REDASH_REDIS_URL
          value: "redis://redis:6379/0"
        - name: REDASH_DATABASE_URL
          value: "postgresql://postgres@postgres/postgres"
        - name: QUEUES
          value: "queries,scheduled_queries,celery,schemas"
        - name: WORKERS_COUNT
          value: "2"
        args: ["scheduler"]