apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: login-deployment
  labels:
    app: login
  namespace: datavis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      restartPolicy: Always
      containers:
      - name: login
        image: guwenqing/datavis-login:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login
  labels:
    app: login
  namespace: datavis
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30092
  selector:
    app: login
  type: NodePort